# Generated by Django 3.2.5 on 2021-08-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_rename_author_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='notas',
            field=models.CharField(default='Sin notas al momento de la creacion', max_length=255),
            preserve_default=False,
        ),
    ]
